#!/bin/bash
trap "exit 1" TERM
export TOP_PID=$$

check_exit_code()
{
    if [ $1 -ne 0 ]; then
        echo "Error"
        kill -s TERM $TOP_PID
    fi
}

echo building bootloader...
winpty python ./bc81asmc/bc81asmc.py --verbose ./bdos/boot.basm
check_exit_code $?

echo building bdos...
./bcc ./bdos/bdos
check_exit_code $?

echo done!