#!/bin/bash
trap "exit 1" TERM
export TOP_PID=$$

check_exit_code()
{
    if [ $1 -ne 0 ]; then
        echo "Error"
        kill -s TERM $TOP_PID
    fi
}

echo building bcos...
python ./bc81asmc/bc81asmc.py --verbose ./bc81asmc/bcOS/bcos.basm
check_exit_code $?

echo converting bcos to rom...
./ftool btap2bin bc81asmc/bcOS/bcos.btap bc81asmc/bcOS/bcos_v1_2_0.b81
check_exit_code $?

echo building bootloader...
winpty python ./bc81asmc/bc81asmc.py --verbose ./bdos/boot.basm
check_exit_code $?

echo building bdos...
./bcc ./bdos/bdos
check_exit_code $?

echo done!