#!/bin/bash
trap "exit 1" TERM
export TOP_PID=$$

check_exit_code()
{
    if [ $1 -ne 0 ]; then
        echo "Error"
        kill -s TERM $TOP_PID
    fi
}

echo creating os disk...
echo converting bootloader to sectors...
./ftool btap2bin bdos/boot.btap bdos/boot.sector
check_exit_code $?

echo converting bdos to sectors...
./ftool btap2bin bdos/bdos.btap bdos/bdos.sector
check_exit_code $?

echo creating empty floppy disk
./ftool createbdd os.bdd
check_exit_code $?

echo burning boot loader to track 0 sector 0
./ftool importsector bdos/boot.sector os.bdd 0 0
check_exit_code $?

echo burning bdos shell to tracks 0-7
./ftool importsector bdos/bdos.sector os.bdd 0 1
check_exit_code $?

echo burning os disc file catalog
./ftool importsector fcat0800.sector os.bdd 8 0
check_exit_code $?

echo burning hello world program
./ftool importsector bdos/helloworld.sectors os.bdd 10 0

echo building ls...
./bcc ./bdos/ls
check_exit_code $?

echo converting ls to sectors...
./ftool btap2bin bdos/ls.btap bdos/ls.sectors
check_exit_code $?

echo burning ls
./ftool importsector bdos/ls.sectors os.bdd 11 0

echo done!